api/__tests__/__snapshots__/profile.spec.ts.snap, api/__tests__/profile.spec.ts, api/src/controllers/namespace.ts, api/src/controllers/profile.ts, api/src/db/model/namespace.ts, api/src/db/model/profile.ts, api/src/libs/utils.ts
Address previous code quality issues.
Fixed #26
=> Fix issues surfaced during previous PR review

README.md, api/scripts/nats-test.ts, api/src/controllers/provision.ts, api/src/db/model/namespace.ts, api/src/router/routes/provision.ts
This change allows for the callback from the namespace provisioning mechanics to the registry API to update the provisioning status of said namespace.
Fixes #33
=> Allow updating provisioning status

api/__tests__/__snapshots__/fulfillment.spec.ts.snap, api/src/constants.ts, api/src/libs/fulfillment.ts
- Change nats message body
- Remove magic numbers
Fixes #96
=> Update NATS message body format and include PO details

web/src/components/DropdownMenu.tsx, web/src/components/DropdownMenuItem.tsx, web/src/components/header.tsx, web/src/index.tsx, web/src/theme.ts
- updating content and CSS stuff based on the following comment from https://github.com/bcgov/platform-services-registry/issues/72:
Please update the menu item under the Create button to: "A new Openshift Project Set/Create 4 project namespaces in Silver cluster" to stay consistent with the existing intake process"
Fixes #72
=> Update the menu item under the Create button as per comment

web/src/AppRouter.tsx, web/src/__tests__/__snapshots__/form.test.tsx.snap, web/src/components/SubFormProject.tsx, web/src/constants.ts, web/src/utils/transformFormData.tsx, web/src/views/Dashboard.tsx, web/src/views/PublicLanding.tsx
* adding optional checkboxes & an input field in order to capture component metadata according to #76
* connecting the values to api call of creating a new profile
* renaming from Home to Dashboard
**Notes:**
* The current form width doesn't seem to accommodate two columns of checkboxes. We could make adjustments - so this part is open to team discussion.
=> Capture component metadata for Platform projects in Project Registry

api/src/controllers/provision.ts, api/src/db/model/cluster.ts, api/src/db/model/namespace.ts, api/src/router/routes/provision.ts
The message body to update the namespace provisioning status has changed for v1 and this PR updates the endpoint accordingly.
Fixes #110
=> Update namespace provisioning callback for new message body

api/__tests__/__snapshots__/fulfillment.spec.ts.snap, api/src/libs/fulfillment.ts
Add the project description to NATS message.
Fixed #114
=> Add description to NATS message

web/src/components/SubFormProject.tsx
- bug fixing so the front-end won't crash if the fetched ministry list is empty
=> Bug fixing on ministry dropdown list

web/src/__tests__/__snapshots__/form.test.tsx.snap, web/src/constants.ts
This PR updates the COMPONENT_METADATA constants to reflect API changes made in PR #103
=> Update COMPONENT_METADATA constants to reflect API changes

api/src/controllers/provision.ts, api/src/db/model/namespace.ts, api/src/db/model/profile.ts, api/src/libs/messaging.ts
Fixes an issue where the namespace ID was being used in place of the profile ID.
=> Fix messaging in provisioning callback

.github/workflows/zap_scan.yml
GitHub Actions job that automatically scans the dev instance weekly for security vulnerabilities.
Fixes  #65
=> Add OWASP ZAP Baseline scan to GitHub Actions

.github/workflows/zap_scan.yml
Update OWASP ZAP Scan CRON frequency
=> Update OWASP ZAP Scan CRON frequency

openshift/templates/nsp.yaml
Add an external network and config so the API can talk to OCP3.
=> Add NSP for API to talk to SSO on the OCP3 cluster

web/src/components/SubFormPO.tsx
This PR rectifies a bug that was discovered regarding the pre-populate PO fields PR. Previously form submission wouldn't work as the PO input fields wouldn't return the pre-populated information. This has since been corrected.
﻿
=> Update pre-populate values to correct state bug

web/src/__tests__/transformDataHelper.test.tsx, web/src/utils/transformDataHelper.tsx, web/src/views/Dashboard.tsx, web/src/views/form.tsx
- fixing the issue so users can see their newly created profile on top on dashboard view
=> Bug fixing for dashboard view feature so the profiles get sorted by the latest datetime

web/src/__tests__/__snapshots__/form.test.tsx.snap, web/src/views/form.tsx
This PR expands the PO description text to describe the importance of the PO submitting the project creation request.﻿
=> Update PO form description

api/src/controllers/profile.ts, api/src/libs/utils.ts
As per issue #145 the profile authorization checks were repetitive. This PR extracts the access control validation to an external function to enable future re usability and expansion.
=> Refactor profile authorization checks to external function

api/__tests__/__snapshots__/contact.spec.ts.snap, api/__tests__/contact.spec.ts, api/doc/api.yaml, api/public/doc/api/index.html, api/src/controllers/contact.ts, api/src/router/routes/contact.ts
This PR enables the ability to update contacts, a requirement of the registry edit feature.
Fixes #137  
Due to API docs being updated:
=> Add updateContact controller

web/src/__tests__/Dashboard.test.tsx, web/src/__tests__/__snapshots__/Dashboard.test.tsx.snap, web/src/__tests__/transformDataHelper.test.tsx, web/src/constants.ts, web/src/utils/promptToastHelper.tsx, web/src/utils/transformDataHelper.tsx, web/src/views/Dashboard.tsx, web/src/views/form.tsx
- making sure only provisioned projects are listed in exported csv
- making sure create and update date are in this format DD-MM-YYYY HH:MM
Fixes #152
=> Project Registry Extract Improvements

web/src/utils/transformDataHelper.tsx
Bugfix to repair prioritySystem flagging fault
=> Add prioritySystem and Component Metadata to transform

api/src/controllers/namespace.ts, api/src/libs/quota-editing.ts
- bug fixing for giving proper default cluster name when sending the request json
=> Bugfix for giving proper default cluster name when sending the request json

web/src/constants.ts, web/src/views/form.tsx
- modifying web form submission component so it gives more specific err message when a submit action fails
- updating dev sso constant on web
Fixes #232
=> Provide a more specific error message when users submit action fails

api/__tests__/__snapshots__/sync.spec.ts.snap, api/__tests__/fixtures/select-request.json, api/__tests__/sync.spec.ts, api/doc/api.yaml, api/public/doc/api/index.html, api/src/controllers/sync.ts, api/src/router/routes/provision.ts
=> Implement API Endpoint to GET Projects that are under Pending Create or Edit (SPIKE)

README.md
This PR adds the Github Actions Test & Build badge as well as the BCGOV Lifecycle badge to the README.md
Fixes #247
=> Add Actions and Lifecycle Badge

web/src/__tests__/ProfileEditable.test.tsx, web/src/components/DropdownMenu.tsx, web/src/components/ProfileEditableQuota.tsx, web/src/components/QuotaCard.tsx, web/src/components/UI/newLineText.tsx, web/src/components/authbutton.tsx, web/src/utils/getValidator.tsx, web/src/utils/transformDataHelper.tsx, web/src/views/form.tsx
- address some of the TODO debt items
- make better TODO comments
- dry QuotaCard react component
- prune / refactor ProfileEditableQuota react component
- minor lint
=> Registry ui refactor work

web/src/components/ProfileEditableProject.tsx
This PR rectifies a onSubmit logic issue (double trigger) and incorporates the refactored redirect logic implemented in the previous PR.
=> Update onSubmit logic, use refactored redirect block

web/src/components/ProfileEditableQuota.tsx, web/src/views/ProfileEditable.tsx
- update the status message to let teams know what's pending
Fixes #224
=> The status message should let teams know what is pending

api/src/db/model/contact.ts, db/seed/data_migration_lowercase.sql
- ensure data written to db for username and email are lower case
- prep a sql to ensure all the past data written in db for username and email are lower case
the above implementations will ensure all PO, TC usernames are lower case in nats message
Fixes #227
=> Both PO and TC user names should be passed to NATS in lower case

web/src/__tests__/Dashboard.test.tsx, web/src/__tests__/ProfileEdit.test.tsx, web/src/__tests__/__snapshots__/Dashboard.test.tsx.snap, web/src/__tests__/fixtures/profile-namespaces.json, web/src/__tests__/transformDataHelper.test.tsx, web/src/constants.ts, web/src/views/Dashboard.tsx
- add quota size field to the project extract report to indicate whether a project has small, medium or large quota sizes
- update unit tests
Fixes #244
=> Add project quota size field to the project report

web/src/AppRouter.tsx, web/src/utils/AppRoute.tsx, web/src/utils/PrivateRoute.tsx
- bugfix so that the logout functionality is working without throwing errors
Fixes #290
=> Fix frontend routes so logout is working without throwing errors

api/__tests__/__snapshots__/profile.spec.ts.snap, api/__tests__/profile.spec.ts, api/src/controllers/profile.ts, api/src/db/model/profile.ts, api/src/libs/authorization.ts, api/src/libs/utils.ts
This PR enables PO/TC to view project details hosted on the registry.
Fixes #139
=> PO/TC Dashboard view enhancement

web/src/__tests__/Dashboard.test.tsx, web/src/components/profileEdit/QuotaCard.tsx, web/src/components/profileEdit/QuotaCardEdit.tsx, web/src/hooks/useRegistryApi.tsx, web/src/types.tsx, web/src/utils/transformDataHelper.tsx, web/src/views/Dashboard.tsx, web/src/views/ProfileEdit.tsx
- adjustment on the web ui side to accommodate quote refactor
- modify around quote-edit submit button so it's greyed out until users make a selection
=> Quota refactor - web ui

api/__tests__/__snapshots__/profile.spec.ts.snap, api/src/db/model/profile.ts
=> Fix the current breaking changes to web portal csv extract

web/src/components/common/UI/CheckboxInput.tsx, web/src/components/profileCreate/CreateFormMetadata.tsx, web/src/components/profileCreate/CreateFormMigration.tsx, web/src/components/profileCreate/CreateFormProject.tsx, web/src/components/profileCreate/CreateFormRequest.tsx, web/src/components/profileEdit/ProjectCardEdit.tsx
This PR rectifies a minor concern involving a checkbox type prop.
=> Update checkbox form props

docs/Project-Set-Resources.md
I've created this doc so we have something to point teams to for information on resources controlled by the registry, and some general information about those resources. Feel free to suggest edits or adjust as necessary.
=> Add Initial Project Set Docs

openshift/templates/nsp.yaml
- allow flyway pre-hook pod to talk to patroni
- change name to `platform-registry`
=> Add additional ingress networkpolicy flyway >> patroni

openshift/templates/nsp.yaml
Migrate the application from NSP to KNP.
=> Migrate application from NSP to KNP

api/__tests__/__snapshots__/cluster.spec.ts.snap, api/__tests__/__snapshots__/project-profile.spec.ts.snap, api/__tests__/cluster.spec.ts, api/__tests__/fixtures/select-default-cluster.json, api/__tests__/project-profile.spec.ts, api/src/controllers/cluster.ts, api/src/controllers/project-profile.ts, api/src/db/model/cluster.ts, api/src/router/index.ts, db/sql/V2.1__multi_cluster.sql, web/src/components/profileCreate/CreateFormProject.tsx, web/src/components/profileEdit/ProjectCard.tsx, web/src/constants.ts, web/src/utils/transformDataHelper.tsx, web/src/views/Dashboard.tsx, web/src/views/ProfileEdit.tsx
Due to the unit test snapshot updates
=> Multi-cluster support feature - Test clusters authorization

api/__tests__/__snapshots__/project-profile.spec.ts.snap, api/__tests__/project-profile.spec.ts, api/src/controllers/project-profile.ts, api/src/libs/authorization.ts, api/src/libs/messaging.ts, api/src/router/routes/profile.ts, api/src/router/routes/provision.ts, web/src/layouts/Layout.tsx, web/src/utils/transformDataHelper.tsx, web/src/views/ProfileEdit.tsx
- refactor around authorization as part of implementation of provisioning test clusters
- web component minor fix
- react-table width issue
- on profileEdit view, switch to a generic error msg because the frontend does not gracefully handle those requested profile ids that do not exist / are not valid
- api component minor fix
- fix hardcoded provisioning cluster in email
- rectify a unit test
=> Multi-cluster support feature - Refactor auth and minor fix

web/src/components/common/layout/Footer.tsx
This PR updates the Contact Us href to link to the Registry GitHub Issues page.
=> WEB UI footer link update

api/src/controllers/sync.ts, api/src/libs/fulfillment.ts
- Main bugfix
- Simplify control so the api code does minimum database transactions
- Minor bugfix
- rectify error message
- rectify handling user input for the cluster name so it serves bad request
Fixes #406
=> Bugfix for sync endpoints

api/src/controllers/sync.ts, api/src/libs/fulfillment.ts
=> Only apply SYNC action name to requests that are already provisioned

api/src/controllers/sync.ts, api/src/libs/fulfillment.ts
Adjustment to the recently done bugfix 8e11c3a36c402fd558523d594db2904aea0cc63f
=> Adjustment to bugfix for action name

.github/workflows/cypress-test.yml
Adding a placeholder workflow to master so that I can then run development versions of the workflow in a feature branch.
=> Add cypress test workflow

api/__tests__/__snapshots__/fulfillment.spec.ts.snap, api/__tests__/__snapshots__/profile.spec.ts.snap, api/__tests__/__snapshots__/quota.spec.ts.snap, api/__tests__/fixtures/get-request-edit-contacts.json, api/__tests__/fixtures/get-request-edit-quota-size.json, api/__tests__/fixtures/select-quota-small.json, api/__tests__/fixtures/select-quota.json, api/__tests__/fulfillment.spec.ts, api/src/db/model/namespace.ts, api/src/db/model/quota.ts, api/src/libs/bot-message.ts, api/src/libs/fulfillment.ts, api/src/types.ts, db/sql/V2.3__add_pvc_count_ref_quota_alter.sql, web/.eslintrc, web/src/components/profileEdit/QuotaCardEdit.tsx, web/src/views/Dashboard.tsx
- Fronted Updated to show PVC Count per Quota Size
Fixes #342 
- API Updated to Pull the PVC Count from the DB and Pass it through NATS
Fixes #341 
- DB Updated with PVC Count field
Fixes #343
=> Add PVC Count Quota Controls to Registry

api/src/controllers/sync.ts, api/src/db/model/request.ts
=> Update pending profiles to find requests not needng human action

api/__tests__/__snapshots__/fulfillment.spec.ts.snap, api/__tests__/__snapshots__/namespace.spec.ts.snap, api/__tests__/fixtures/select-project-set-namespaces.json, api/__tests__/fulfillment.spec.ts, api/__tests__/sync.spec.ts, api/src/constants.ts, api/src/controllers/project-profile.ts, api/src/controllers/provision.ts, api/src/controllers/sync.ts, api/src/db/model/namespace.ts, api/src/libs/bot-message.ts, api/src/libs/fulfillment.ts, api/src/libs/namespace.ts, api/src/libs/utils.ts, db/sql/V2.5__add_archived_golddr.sql, web/src/components/common/UI/FormControls.tsx, web/src/components/profileCreate/CreateFormGoldModal.tsx, web/src/components/profileCreate/CreateFormProject.tsx, web/src/hooks/useRegistryApi.tsx, web/src/utils/transformDataHelper.tsx, web/src/views/ProfileCreate.tsx
This PR introduces the ability to provision the same project in two clusters. This is necessary for the eventual rollout of Gold / Gold DR. KLAB has been configured to allow for the optional generation of a matching namespace in CLAB.
Fixes #432, Fixes #408
=> Multi cluster replication

web/src/components/common/layout/Footer.tsx, web/src/constants.ts, web/src/views/Dashboard.tsx
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/277
=> FED-227 Add a report bug link on footer

api/__tests__/lib-request.spec.ts, api/__tests__/profile.spec.ts, api/src/controllers/profile.ts, api/src/libs/request.ts, web/src/__tests__/ContactCard.test.tsx, web/src/__tests__/__snapshots__/ContactCard.test.tsx.snap, web/src/__tests__/__snapshots__/ProfileCreate.test.tsx.snap, web/src/__tests__/__snapshots__/ProfileEdit.test.tsx.snap, web/src/__tests__/__snapshots__/ProjectCard.test.tsx.snap, web/src/components/common/UI/FormTitle.tsx, web/src/components/profileEdit/ContactCard.tsx, web/src/components/profileEdit/ContactCardEdit.tsx, web/src/components/profileEdit/ProjectCard.tsx, web/src/components/profileEdit/ProjectCardEdit.tsx, web/src/utils/transformDataHelper.tsx, web/src/views/ProfileCreate.tsx, web/src/views/ProfileEdit.tsx
This PR implements the capability to add or edit multiple technical leads to a project during the edit process.
** NOTE: This PR is the depends upon Multiple Technical Leads (Create) **
Fixes #450
=> Multiple Technical Leads (Edit)

api/src/db/model/profile.ts
Ministry Model had wrong type. This will need to be updated in the Model abstract too as reflected in ticket #469 
Fixes #357
=> Update busOrgId interface to string

web/package-lock.json, web/package.json, web/src/components/common/UI/AuthButton.tsx, web/src/views/PublicLanding.tsx
Ticket: https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/324
=> FED-324 new user landing page

api/__tests__/__snapshots__/project-profile.spec.ts.snap, api/__tests__/lib-request.spec.ts, api/__tests__/profile.spec.ts, api/__tests__/project-profile.spec.ts, api/src/constants.ts, api/src/controllers/profile.ts, api/src/controllers/project-profile.ts, api/src/controllers/provision.ts, api/src/controllers/request.ts, api/src/db/model/profile.ts, api/src/libs/profile.ts, api/src/libs/request.ts, db/sql/V2.6__add_profile_status.sql, web/src/components/profileEdit/ContactCardEdit.tsx, web/src/utils/transformDataHelper.tsx, web/src/views/Dashboard.tsx, web/src/views/ProfileCreate.tsx
This PR introduces enhanced profile status details including: pending edit, pending approval, approved, and provisioned. This will allow for an improved user experience and improve the UI's capability to categorize projects.
=> Enhanced project status

web/src/__tests__/__snapshots__/Dashboard.test.tsx.snap, web/src/components/common/UI/Icon.tsx, web/src/components/common/UI/Table.tsx, web/src/components/common/UI/Tooltip.tsx, web/src/components/dashboard/ProjectDetails.tsx, web/src/components/dashboard/ProjectRequests.tsx, web/src/components/profileEdit/ContactCardEdit.tsx, web/src/types.tsx, web/src/views/Dashboard.tsx, web/src/views/ProfileEdit.tsx
This PR introduces a dashboard table search capability as well as additional column views.
Users will be able to select from the following columns, with the last two hidden by default but still searchable:
Name
Description
Ministry
Cluster
Product Owner
Technical Contact
Status
Namespace*
Quota*
Side feature: A back button has been added to the Project Overview page also.
Fixes #155
=> Dashboard filter and search

web/src/components/common/UI/Button.tsx, web/src/components/common/UI/CheckboxInput.tsx, web/src/components/profileEdit/QuotaCardEdit.tsx, web/src/views/ProfileEdit.tsx
Ticket : https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/355
=> Add a link to the quota increase document

api/src/services/profile.ts, web/src/views/Dashboard.tsx
When we don't have any profile in db, we need to return some array even it is empty before we start loop through
=> handle edge case(empty db)

web/src/components/common/UI/Table.tsx, web/src/components/dashboard/ProjectDetails.tsx, web/src/components/dashboard/ProjectRequests.tsx, web/src/hooks/useHandleSort.tsx
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1603
=> User our own sort instead of using react-table sort

web/src/__tests__/__snapshots__/Dashboard.test.tsx.snap, web/src/views/Dashboard.tsx
Reverts bcgov/platform-services-registry#510
=> Revert "test"

web/src/components/common/UI/Table.tsx
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1604
=> Registry Dashboard Contact Search

web/openshift/templates/config.yaml
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/521
=> add caddy cache control field/strategy

db/flyway.Dockerfile
Changing flyway from version 7.5.3 to 8.4.1
=> Update flyway version due to H2 vulnerability

db/sql/V4.4__downgrade_silver_quota.sql
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/2205
=> Migration script for silver tools quota

web/src/components/profileCreate/CreateFormTL.tsx, web/src/components/profileEdit/ContactCardEdit.tsx
In create as well as edit contexts.
Pretty darn straightforward.
=> Technical Lead fields now say (Primary) or (Secondary) as appropriate

web/src/components/common/layout/Header.tsx, web/src/constants.ts
https://github.com/BCDevOps/developer-experience/issues/2367
=> Block github keycloak token

web/src/components/dashboard/PSRDocumentationLink.tsx, web/src/views/Dashboard.tsx
This linted perfectly. Someone approve this merge.
=> Link to help documentation #645

api/__tests__/__snapshots__/fulfillment.spec.ts.snap, api/src/libs/fulfillment.ts
Reverts bcgov/platform-services-registry#667
=> Revert "Deletiontest"

api/src/controllers/request.ts, api/src/controllers/sync.ts, db/sql/V4.6__fix_bad_entry_in_request.sql
Deletion feature is not marking requests as done. There are 3 tests done by Ian and I, so 3 entry need to be fixed.(888 884 886)
=> Fix database filter request

web/src/components/profileEdit/ContactCardEdit.tsx
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/686
=> Allow user directly add primary TL.

.github/workflows/dev-web.yml, .github/workflows/promote_to_test-v2.yml, web/cypress.config.ts, web/package-lock.json, web/package.json
Cypress version update breaked the github action. Disable it for now.
=> Fix GitHub action cypress

web/src/utils/getValidator.tsx
Adjusts the email character limit to 40 characters.
=> adjusted email character limit to 40 characters

openshift/README.md
Based on  what you showed me during our call today.
=> update readme to discuss schema updates and flyway migration.

web/src/utils/getValidator.tsx
This fixes the issue with the inclusion of spaces and dashes in names.
=> added dashes and spaces availability for names

web/src/components/common/UI/EditSubmitButton.tsx, web/src/components/profileEdit/QuotaCardEdit.tsx
Closes #728  added additional check on disabled button based on react final form properties
=> quata change checkbox ignore

web/src/components/common/UI/EditSubmitButton.tsx, web/src/components/profileEdit/QuotaCardEdit.tsx
Reverts bcgov/platform-services-registry#767
This PR introduced a bug described in #782
=> Revert "quata change checkbox ignore"

README.md
Hi, Alex and Oamar. I updated the main readme to more accurately reflect the changes to the product regarding searching for contacts with the Graph API, and configuration that needs to be done (which is really just declaring a redirect uri pointing to back the product itself).
=> Update to graph/azure section of README

web/package-lock.json, web/package.json, web/src/components/profileEdit/ContactCardEdit.tsx
Hi, Oamar. Mind having a quick look so I can close out this ticket?
=> Idir explanation on edit contacts

web/src/views/Dashboard.tsx
Hi, Billy. 
I think this is what you had in mind, but one thing I'm not sure about is how searching for elements by className in React works for external stuff, like entity. 
Let me know if you need me to rework this.
=> div with classname appears when profiles fetched

web/src/components/profileCreate/CreateFormTL.tsx
Test environment seems to get a few null reference exceptions, but not dev. Might as well be double sure and include more null checking.
=> More null checking on create form tl.tsx

web/src/components/profileCreate/CreateFormPO.tsx, web/src/redux/githubID/githubID.action.ts, web/src/redux/githubID/githubID.reducer.ts
"User Not Found :(" now appears again when no user is found when searching on IDIR users
=> Fix 'user not found' not showin up

api/__tests__/__snapshots__/fulfillment.spec.ts.snap, api/src/libs/fulfillment.ts, api/src/types.ts
=> Alliance message jag

app/login/page.tsx
Fixed the gap between paragraphs
Fixed the escaped brackets
TODO: Sign out button is not rendered properly when signed in
=> Fixed formatting issues

README.md
Added the "Maturing" lifecycle badge into the readme
=> Added project lifecycle badge to README

.github/workflows/deploy-dev.yml, .tool-versions, Dockerfile, helm/.gitignore, helm/_app/.helmignore, helm/_app/Chart.yaml, helm/_app/templates/_helpers.tpl, helm/_app/templates/deployment.yaml, helm/_app/templates/hpa.yaml, helm/_app/templates/route.yaml, helm/_app/templates/service.yaml, helm/_app/values.yaml, helm/main/.helmignore, helm/main/Chart.lock, helm/main/Chart.yaml, helm/main/Makefile, helm/main/templates/_helpers.tpl, helm/main/templates/mongodb-secret.yaml, helm/main/templates/networkpolicy.yaml, helm/main/values-101ed4-dev.yaml, helm/main/values.yaml, package-lock.json, package.json
- Helm chart to generate the k8s objects
- GitHub Action to deploy app in dev environment
=> feat: add deployment helm charts

app/api/private-cloud/create/route.ts, app/api/private-cloud/decision/[licencePlate]/route.ts, app/api/private-cloud/edit/[licencePlate]/route.ts, app/api/public-cloud/create/route.ts, app/api/public-cloud/decision/[licencePlate]/route.ts, app/api/public-cloud/edit/[licencePlate]/route.ts, jest.config.mjs, jest.setup.js, mautic/index.ts, requestActions/private-cloud/createRequest.ts, requestActions/private-cloud/decisionRequest.ts, requestActions/private-cloud/editRequest.ts, requestActions/public-cloud/createRequest.ts, requestActions/public-cloud/decisionRequest.ts, requestActions/public-cloud/editRequest.ts, tsconfig.json
- Implemented Mautic
- Refactored api routes to handle mautic errors without returning a bad api status to the front end
=> Implemented Mautic mail subscription service

docs/developer-guide.md, docs/team-conventions.md
Conventional Commits provide a structured way to format commit messages. This improves readability, enables automated processes like changelog generation and versioning, and enhances collaboration through clearer communication in code repositories.
- Please refer to https://www.conventionalcommits.org/ for more detailed information.
- `feat(user-auth): add password reset functionality`
- `fix(validation): handle edge case in email input`
- `chore(tests): update unit tests for user service`
- `refactor(api): optimize database queries in user endpoints`
- `docs(readme): update installation instructions`
- `chore(deps): update package versions for security patch`
- `chore(deps): update package versions for security patch`
- `BREAKING CHANGE: remove support for Node.js v10`
A Git branching …
=> docs: update team conventions

helm/main/templates/mongodb-secret.yaml, helm/main/values.yaml
ref: https://docs.developer.gov.bc.ca/platform-storage/
=> ci: use netapp-block-standard as db storage

app/(request)/private-cloud/decision/[licencePlate]/page.tsx, app/(request)/private-cloud/edit/[licencePlate]/page.tsx, app/(request)/private-cloud/request/[id]/page.tsx, app/(request)/public-cloud/decision/[licencePlate]/page.tsx, app/(request)/public-cloud/edit/[licencePlate]/page.tsx, app/(request)/public-cloud/request/[id]/page.tsx, components/Provider.tsx, components/form/AsyncAutocomplete.tsx, components/nav/ProfileDropdown.tsx, package-lock.json, package.json
- ref: https://tanstack.com/query/v5/docs/react/guides/migrating-to-v5#supports-a-single-signature-one-object
=> refactor(1235): update useQuery syntax accordingly to the new version

ches/chesService.ts, ches/emailHandler.ts, nats/privateCloud/index.test.ts
The send email function will internally handle errors that will not propagate
=> Fixed email error handling

app/api/private-cloud/create/route.ts
Email's still seem to be causing issues in dev. Lets just comment it out for now and see if it resolves the error, then we know for sure it is the problem.
=> commented out emails

app/(dashboard)/private-cloud/products/page.tsx, app/(dashboard)/private-cloud/requests/page.tsx, app/(dashboard)/public-cloud/products/page.tsx, app/(dashboard)/public-cloud/requests/page.tsx, components/buttons/PaginationButtons.tsx, components/table/TableBody.tsx
=> feat(897): add rows per page selection on paginations

app/(dashboard)/private-cloud/products/page.tsx, app/(dashboard)/private-cloud/requests/page.tsx, app/(dashboard)/public-cloud/products/page.tsx, app/(dashboard)/public-cloud/requests/page.tsx, app/api/private-cloud/create/route.test.ts, app/api/private-cloud/decision/[licencePlate]/route.test.ts, app/api/private-cloud/delete/[id]/route.ts, app/api/private-cloud/edit/[licencePlate]/route.ts, app/api/private-cloud/requests/route.ts, app/api/public-cloud/edit/[licencePlate]/route.ts, package-lock.json, package.json, queries/paginated/private-cloud/index.test.ts, queries/paginated/private-cloud/index.ts, queries/paginated/public-cloud/index.ts, queries/private-cloud/helpers.ts, queries/private-cloud/index.test.ts, queries/private-cloud/index.ts, queries/user.ts
ministry roles functionality added
=> feat: add ministry role access logic

docs/clean-codes/return-early.md
The `Return Early` pattern for functions is a programming practice where you structure your code in such a way that you check for certain conditions at the beginning of a function and return immediately if those conditions are met. This pattern is often used to improve code readability, reduce nesting, and make the code more concise.
Here are some benefits of using the `Return Early` pattern:
1. `Improved Readability`: By checking for special cases or error conditions at the beginning of a function and returning early, you make the code easier to read and understand. Developers can quickly grasp the main flow of the function without getting bogged down in nested if statements.
2. `Reduced Nesting`: Avoiding deep nesting of if statements or other control structures makes the code more …
=> docs(clean-codes): add return-early-pattern

emails/RequestProvisioned.tsx, emails/components/Params.ts, emails/components/ProductDetails.tsx, emails/templates/ProvisionedTemplate.tsx
=> request provisioned email template added

app/layout.tsx, components/Footer.tsx, components/FooterLarge.tsx, components/table/TableBody.tsx
- Table height is now fixed, this means that the table will not shift when going to the next page
- Added the footer
=> Added footer and fixed table height

.eslintrc.json, components/buttons/SecondTechLeadButton.tsx, components/form/AccountCodingInput.tsx, components/form/AsyncAutocomplete.tsx, components/form/Budget.tsx, components/modal/CreatePrivateCloud.tsx, components/modal/CreatePublicCloud.tsx, components/modal/EditPrivateCloud.tsx, components/nav/CrumbsNav.tsx
ref: https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete#values
=> chore: fix jsx-a11y lints

.codespellrc, .pre-commit-config.yaml, app/api/private-cloud/decision/[licencePlate]/route.ts, app/api/private-cloud/edit/[licencePlate]/route.ts, app/api/private-cloud/provision/[licencePlate]/route.ts, app/api/public-cloud/decision/[licencePlate]/route.ts, app/api/public-cloud/edit/[licencePlate]/route.ts, app/api/public-cloud/provision/[licencePlate]/route.ts, app/login/page.tsx, components/form/AsyncAutocomplete.tsx, components/nav/Nav.tsx, docs/developer-guide.md, emails/templates/private-cloud/RequestApproval.tsx, emails/templates/public-cloud/RequestApproval.tsx, localdev/keycloak-provision/setup.js, queries/paginated/private-cloud/index.ts, queries/private-cloud/index.ts, requestActions/private-cloud/editRequest.ts, scripts/deletioncheck.ts
- `codespell` is designed to find and fix common misspellings in text files
=> ci: add codespell check

app/(dashboard)/public-cloud/requests/page.tsx, components/form/Budget.tsx, components/form/Comment.tsx, components/form/ProjectDescriptionPrivate.tsx, components/form/ProjectDescriptionPublic.tsx, components/form/Quotas.tsx, components/form/TeamContacts.tsx
1) fixed spacing
2) fixed spacing between the hyperlink
3) added "in" to the sentence
4) the email link was commented out, removed the comment, is this email supposed to be updated ? (cloud.pathfinder@gov.bc.ca)
5) corrected spelling of "descriptive"
6) removed info in brackets 
7) project is now "product"
8) corrected placeholders with their correct labels respectively
9) corrected typos and updated email to platformservicesteam@gov.bc.ca
10) not sure of the changes that need to be made here, the page matches the current figma mockups
11) all mentions of Sal now removed, and instead has the respective email listed
12) added a comma for clarity
13) corrected the suffixes, changed link to a span field instead 
14) table rework negates this issue ?
=> various small visual bug fixes

app/(dashboard)/public-cloud/products/page.tsx, components/table/FilterPanel.tsx, constants/index.ts
filter for public cloud with provider, not cluster
=> filter for public clo9ud provider

app/(request)/private-cloud/decision/[licencePlate]/page.tsx, app/(request)/private-cloud/edit/[licencePlate]/page.tsx, app/(request)/public-cloud/decision/[licencePlate]/page.tsx, app/(request)/public-cloud/edit/[licencePlate]/page.tsx, components/buttons/SubmitButton.tsx, components/modal/EditPrivateCloud.tsx, components/modal/ReturnDecision.tsx, queries/paginated/private-cloud/index.ts, queries/paginated/public-cloud/index.ts, queries/private-cloud/helpers.ts
22
-----
Wording for create
Wording for edit
Wording for decision (approving/denying a create or edit)
24
-----
Edit no longer mentions quota change
Also added a formstate check to the button to see if there have been changes made to the edit form, otherwise the button will be disabled.
=> feat: new modal for approve/deny an edit request.

nats/privateCloud/constants.ts, nats/privateCloud/index.ts
There was a quota missing in the constants for the nats message. I have added that quota and also added types to the constants.
=> Added types for nats message quota

components/form/AccountCoding.tsx, components/form/AsyncAutocomplete.tsx, components/form/CommonComponents.tsx, schema.ts
- Submit button is now disabled for edit request until an input it changed (for private cloud)
- User autocomplete now shows the first name and last name
=> fixed disable submit on dirty and autocomplete not showing names

.github/workflows/deploy-dev.yml, .github/workflows/deploy-test.yml, .gitignore, docs/react-email.md, helm/_email/.helmignore, helm/_email/Chart.yaml, helm/_email/templates/_helpers.tpl, helm/_email/templates/deployment.yaml, helm/_email/templates/hpa.yaml, helm/_email/templates/route.yaml, helm/_email/templates/service.yaml, helm/_email/values.yaml, helm/main/Chart.lock, helm/main/Chart.yaml, helm/main/Makefile, helm/main/values-101ed4-dev.yaml, helm/main/values-101ed4-prod.yaml, helm/main/values-101ed4-test.yaml, helm/main/values.yaml
- dev: https://dev-pltsvc-email.apps.silver.devops.gov.bc.ca/
=> ci: deploy email dashboard

app/api/private-cloud/all-projects/route.test.ts, app/api/private-cloud/all-projects/route.ts, app/api/public-cloud/all-projects/route.test.ts, app/api/public-cloud/all-projects/route.ts, components/table/SearchFilterSort.tsx
- Jest tests that cover the base cases for the csv download for public cloud
- Public cloud now properly handles the error of zero projects being downloaded
- Private + Public cloud both now have respective file names for csv download
=> test: jest tests for public cloud csv + bug fixes

app/(request)/public-cloud/decision/[licencePlate]/page.tsx
=> updated reject modal for public cloud

app/(request)/private-cloud/edit/[licencePlate]/page.tsx, components/modal/EditPrivateCloud.tsx
=> bug: fixed edit request window modal

app/(request)/public-cloud/decision/[licencePlate]/page.tsx, components/modal/Comment.tsx, components/modal/ReturnDecision.tsx
Before
After
When approving
When rejecting
=> public cloud approve modal now updated and dynamic

.env.example, core/modelService.ts, core/services/index.ts, core/services/privateCloudProject.ts, core/services/privateCloudProjectZapResult.ts, core/services/privateCloudRequestedProject.ts, core/services/publicCloudProject.ts, core/services/publicCloudRequest.ts, core/services/publicCloudRequestedProject.ts, lib/prisma.ts, prisma/schema.prisma
- refactor `prisma` security layer implementation
- add security service layer for `privateCloudProjectZapResult`
=> feat: add security service layer for privateCloudProjectZapResult

helm/main/values-101ed4-dev.yaml, helm/main/values-101ed4-prod.yaml, helm/main/values-101ed4-test.yaml
Change Provisioner NATS url for Dev, Test and Prod
=> Change Provisioner NATS url for Dev, Test and Prod

app/(request)/private-cloud/decision/[licencePlate]/page.tsx
=> fix: private cloud decision page now has corrected modal

app/(product)/private-cloud/(product)/layout.tsx, app/(product)/private-cloud/(product)/security/[licencePlate]/layout.tsx, app/(product)/private-cloud/(product)/security/[licencePlate]/repository/page.tsx, app/(product)/private-cloud/(product)/security/[licencePlate]/zap/page.tsx, app/(product)/public-cloud/(product)/layout.tsx, app/api/auth/options.ts, app/api/security-config/[licencePlate]/route.ts, app/api/security-config/route.ts, app/layout.tsx, config.ts, core/services/index.ts, core/services/securityConfig.ts, package-lock.json, package.json, prisma/schema.prisma, schema.ts, services/axios.ts, services/security-config.ts, types/next-auth.d.ts
=> feat(1728): update security - repository tab

app/sonarscan/layout.tsx, app/sonarscan/results/SearchPanel.tsx, app/sonarscan/results/loading.tsx, app/sonarscan/results/page.tsx, core/services/index.ts, core/services/privateCloudProjectZapResult.ts, core/services/sonarScanResult.ts, docs/team-conventions.md, prisma/schema.prisma, security-dashboard/sonarscan/entrypoint.sh
=> feat: add sonarscan result page

.github/workflows/deploy-dev.yml, .github/workflows/deploy-test.yml, Dockerfile, components/Footer.tsx
- add app version # in the footer to track of the application version.
=> feat: add version # in footer

app/(product)/private-cloud/layout.tsx, components/nav/CrumbsNav.tsx
back button from public/product page forward to all products dashboard
=> back arrow to all products

components/buttons/LoginButton.tsx, components/nav/ProfileDropdown.tsx, components/zapscan/ZapScanResults.tsx, helm/secdash/dags/projects.py, helm/secdash/dags/sonarscan-dev.py, helm/secdash/dags/zapscan-dev.py, helm/secdash/dags/zapscan-prod.py, helm/secdash/dags/zapscan-test.py, security-dashboard/sonarscan/entrypoint.sh, security-dashboard/zap/Dockerfile, security-dashboard/zap/entrypoint.sh
=> chore: update airflow DAGs

components/table/TableBodyAWSRoles.tsx
link mailto for users emails aws dashboard
=> mailto for users emails

helm/_app/templates/deployment.yaml
added AWS roles secrets stored in vault
=> added AWS secrets

helm/main/values-101ed4-test.yaml
Add Dev CHES URLs to Test pltsvc to fix emails on Test for now
=> Add Dev CHES URLs to Test pltsvc to fix emails on Test for now

helm/_app/templates/deployment.yaml
Adding Env Vars from Vault for Pre-Deletion Check
=> Adding Env Vars from Vault for Pre-Deletion Check

components/sonarscan/SearchPanel.tsx, components/zapscan/SearchPanel.tsx, lib/query-string.ts
- it fixes an issue of infinite redirections between two tabs due to the navigation delays.
=> chore: fix tab redirections issue

ches/public-cloud/emailHandler.ts, emails/PublicCloudAdminDeleteRequests.tsx, emails/PublicCloudEditRequest.tsx, emails/_components/Edit/BudgetChanges.tsx, emails/_components/Edit/ContactChanges.tsx, emails/_components/Edit/DescriptionChanges.tsx, emails/_templates/public-cloud/AdminDeleteRequest.tsx, emails/_templates/public-cloud/EditSummary.tsx
An email template to alert admins of the public cloud that a delete request has been put in for a particular product.
=> feat: delete request email for admins of public cloud

emails/_components/TailwindWrapper.tsx, emails/_templates/private-cloud/RequestApproval.tsx
added Head for tailwind as wrapper for one of templates, some edits for the same template based on test feedback
=> Head for tailwind as wrapper

app/api/public-cloud/delete/[licencePlate]/route.ts, emails/_components/Edit/quotaLookup.ts, emails/_components/NamespaceDetails.tsx, emails/_templates/private-cloud/Provisioned.tsx, emails/_templates/private-cloud/RequestApproval.tsx, emails/_templates/private-cloud/RequestRejection.tsx, emails/_templates/public-cloud/Provisioned.tsx, emails/_templates/public-cloud/RequestApproval.tsx, emails/_templates/public-cloud/RequestRejection.tsx
Content changes to a few emails
adminDeleteRequest email now added to route for public cloud
=> fix: wording, and admin delete email

helm/secdash/Makefile, helm/secdash/dags/_acs_api.py, helm/secdash/dags/projects.py, helm/secdash/dags/sonarscan-dev.py, helm/secdash/dags/sonarscan-prod.py, helm/secdash/dags/sonarscan-test.py, helm/secdash/dags/zapscan-dev.py, helm/secdash/dags/zapscan-prod.py, helm/secdash/dags/zapscan-test.py
- prevent request timeout errors
- share the sonarqube results through multiple projects
=> chore: update security dashboard dags

components/table/SearchFilterSort.tsx
prevent page reboot on hitting "Enter" button in search input field
=> prevent page reboot on search

app/(product)/public-cloud/(product)/aws-roles/[licencePlate]/[role]/page.tsx, app/api/public-cloud/aws-roles/helpers.ts, components/modal/DeleteUser.tsx, components/table/TableBodyAWSRoles.tsx, package-lock.json
public clpoud team asked to remove public cloud product related users from aws-roles users list
=> removed public cloud product related users from aws-roles users list

analytics/private-cloud/quotaChanges.ts
Fixed analytics dashboard for quota edit requests
=> Analytics fix

emails/_templates/private-cloud/CreateRequest.tsx, emails/_templates/private-cloud/DeleteApproval.tsx, emails/_templates/private-cloud/DeleteRequest.tsx, emails/_templates/private-cloud/EditRequest.tsx, emails/_templates/private-cloud/Provisioned.tsx, emails/_templates/private-cloud/RequestApproval.tsx, emails/_templates/private-cloud/RequestRejection.tsx, emails/_templates/public-cloud/AdminCreateRequest.tsx, emails/_templates/public-cloud/AdminRequest.tsx, emails/_templates/public-cloud/CreateRequest.tsx, emails/_templates/public-cloud/DeleteApproval.tsx, emails/_templates/public-cloud/DeleteRequest.tsx, emails/_templates/public-cloud/EditSummary.tsx, emails/_templates/public-cloud/Provisioned.tsx, emails/_templates/public-cloud/RequestApproval.tsx, emails/_templates/public-cloud/RequestRejection.tsx
To view the progress of changes for Registry emails please check zenhub ticket: 
https://app.zenhub.com/workspaces/app-dev-team-646fdb4400ed8c0021aceeb4/issues/gh/bcgov/platform-services-registry/1978
The review also includes general spelling and grammatical updates for easier reading and consistency
=> registry email templates update

emails/_components/Closing.tsx, emails/_templates/public-cloud/CreateRequest.tsx, emails/_templates/public-cloud/DeleteApproval.tsx, emails/_templates/public-cloud/DeleteRequest.tsx, emails/_templates/public-cloud/EditSummary.tsx, emails/_templates/public-cloud/Provisioned.tsx, emails/_templates/public-cloud/RequestApproval.tsx, emails/_templates/public-cloud/RequestRejection.tsx
=> email footer wording changed

app/api/auth/options.ts, app/api/msal/userImage/route.ts, app/api/public-cloud/aws-roles/helpers.ts, components/form/AsyncAutocomplete.tsx, components/modal/AddUser.tsx, helpers/mock-users.ts, msal/service.ts, types/user.ts
- clean up codebase so that application pages use `AppUser` to match the field names
=> feat: clean up ms query data

analytics/private-cloud/products.ts, analytics/private-cloud/quota-changes.ts, analytics/private-cloud/request-decision-time.ts, analytics/private-cloud/requests.ts, analytics/public-cloud/products.ts, analytics/public-cloud/request-decision-time.ts, analytics/public-cloud/requests.ts, app/(analytics)/private-cloud/analytics/page.tsx, app/(analytics)/public-cloud/analytics/page.tsx, app/api/private-cloud/all-projects/route.ts, app/api/private-cloud/analytics/csv/decision-time/route.ts, app/api/private-cloud/analytics/csv/products/route.ts, app/api/private-cloud/analytics/csv/quota-request-users/route.ts, app/api/private-cloud/analytics/csv/quota-requests/route.ts, app/api/private-cloud/analytics/csv/requests/route.ts, app/api/public-cloud/all-projects/route.ts, app/api/public-cloud/analytics/csv/decision-time/route.ts, app/api/public-cloud/analytics/csv/products/route.ts, app/api/public-cloud/analytics/csv/requests/route.ts, components/analytics/LineGraph.tsx, core/responses.ts, utils/date.ts
- enhance/fix analytics pages
- add csv response handler
=> feat: enhance analytics pages

helm/main/Chart.lock, helm/main/Chart.yaml, helm/main/Makefile, localdev/nats-provision/setup.js
We have `make upgrade-db ...` to upgrade database independently.
=> feat: add update-db make script

app/(product)/public-cloud/(product)/layout.tsx, components/form/ExpenseAuthority.tsx, request-actions/public-cloud/create-request.ts, request-actions/public-cloud/decision-request.ts, request-actions/public-cloud/edit-request.ts, schema.ts
aws-roles and expense authority are available at prod
=> aws-roles and expense authority are available at prod 

app/api/public-cloud/decision/[licencePlate]/route.ts, app/api/public-cloud/edit/[licencePlate]/route.ts, app/api/public-cloud/provision/[licencePlate]/route.ts, emails/PublicCloudExpenseAuthority.tsx, emails/_templates/public-cloud/ExpenseAuthority.tsx, services/ches/public-cloud/email-handler.ts
add email notification for expense authority
=> chore: add email notification for expense authority

app/(product)/public-cloud/create/page.tsx, terraform/keycloak/dev/ministry-roles.tf, terraform/keycloak/prod/ministry-roles.tf, terraform/keycloak/test/ministry-roles.tf
citz and hlth are replaced with ag ministry roles
=> replace citz and hlth with ag ministry roles

components/table/TableBodyProducts.tsx
I found out that tooltip was show for multiple rows when clicked on one of them. I made a fix for that.
=> fix(frontend): fix tooltip shown for multiple rows

components/modal/Comment.tsx, components/modal/PublicCloudDelete.tsx, docs/email-scenarios-private-cloud.md, emails/_templates/private-cloud/AdminCreateRequest.tsx, emails/_templates/private-cloud/Provisioned.tsx, services/ches/private-cloud/email-handler.ts
Comment is optional for create request, removed comment for approve request case  
Added product name for a create request rejection email subject, undated docs
=> chore: private cloud create request emails enhancement

app/(product)/private-cloud/(product)/[licencePlate]/comments/page.tsx, app/(product)/private-cloud/(product)/layout.tsx, components/comments/CommentForm.tsx, core/auth-options.ts, services/backend/private-cloud.ts, types/next-auth.d.ts
1. New tab for a comments section on the product page
2. See all comments associated with that product
3. Add new comments to the product using a text box
=> Basic UI implementation of the comments section

app/private-cloud/products/(product)/[licencePlate]/comments/page.tsx, components/comments/CommentBubble.tsx, components/comments/CommentForm.tsx, package-lock.json, package.json
=> comments bubble UI component

app/api/private-cloud/products/[licencePlate]/deletion-check/route.ts, app/api/private-cloud/provision/[licencePlate]/route.ts, app/api/public-cloud/aws-roles/helpers.ts, config.ts, core/api-handler.ts, core/logging.ts, package-lock.json, package.json, services/ches/helpers.ts, services/ches/private-cloud/email-handler.ts, services/ches/public-cloud/email-handler.ts, services/db/user.ts, services/mautic/index.ts, services/msgraph/core.ts, types/jwt.ts
ex)
```json
{"level":"error","message":"my error","stack":"Error: my error\n    at eval (webpack-internal:///(rsc)/./app/api/example/[color]/route.ts:25:11)\n    at eval (webpack-internal:///(rsc)/./core/api-handler.ts:103:30)\n    at async /home/ahnjun/projects/platform-services-registry/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:53446\n    at async e_.execute (/home/ahnjun/projects/platform-services-registry/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:44747)\n    at async e_.handle (/home/ahnjun/projects/platform-services-registry/node_modules/next/dist/compiled/next-server/app-route.runtime.dev.js:6:54700)\n    at async doRender (/home/ahnjun/projects/platform-services-registry/node_modules/next/dist/server/base-server.js:1377:42)\n …
```
=> feat(2249): add logger for backend

app/private-cloud/products/(product)/[licencePlate]/comments/page.tsx, components/comments/CommentBubble.tsx, package-lock.json
=> feat(comments): edit a comment through the UI

components/form/GolddrCheckbox.tsx, components/generic/checkbox/FormCheckbox.tsx
by selecting `No`, it will revert the status.
=> feat: add confirmation in checkbox component

app/private-cloud/products/(product)/[licencePlate]/edit/page.tsx, app/private-cloud/products/(product)/create/page.tsx, components/form/CommonComponents.tsx, components/form/ProjectDescriptionPublic.tsx
**Before (wrong numbering of sections)**
**After (correct numbering of sections)**
=> fix(2813): add dynamic numbering to Common Components section

app/login/page.tsx, app/private-cloud/products/(product)/layout.tsx, app/public-cloud/products/(product)/layout.tsx, components/form/GolddrCheckbox.tsx, components/generic/checkbox/FormCheckbox.tsx, package-lock.json
=> fix(2835): add dynamic wording for gold dr check box

app/app/api/private-cloud/products/[licencePlate]/comments/_operations/list.ts, app/app/private-cloud/products/(product)/[licencePlate]/comments/page.tsx, app/app/private-cloud/products/(product)/[licencePlate]/layout.tsx, app/app/private-cloud/requests/(request)/[id]/comments/page.tsx, app/app/private-cloud/requests/(request)/[id]/layout.tsx, app/components/comments/CommentBubble.tsx, app/components/comments/CommentForm.tsx, app/prisma/schema.prisma, app/services/backend/private-cloud/products.ts
=> feat(2958): add frontend support for admin comments on requests

app/components/Landing.tsx, app/package-lock.json
=> refactor: update landing page content

app/components/form/QuotaInput.tsx
=> feat(3034): hide current resource info on non-editable form

app/app/private-cloud/products/(product)/[licencePlate]/comments/page.tsx, app/app/private-cloud/requests/(request)/[id]/comments/page.tsx
=> bug(3173): fix incorrect profile image mapping in admin comments section

app/components/comments/CommentBubble.tsx
1. editing now refetches the updated comment
2. newlines are now captured in edit mode
3. newlines are now displayed in edit mode
=> fix(3174): fix newlines in edit text area and refetching of edited comments

helm/secdash/dags/mark_provisioned.py, helm/secdash/dags/provisioner-prod.py, helm/secdash/dags/provisioner-test.py
Add the tested in Airflow backend 'backup callback' logic and two DAGs, one for Test (tested in Airflow, triggered manually) and one for Prod
=> feat(3145): integrate the provisioner script into Airflow DAGs

app/analytics/general/login.ts, app/app/analytics/page.tsx, app/app/api/analytics/csv/login/route.ts, app/components/layouts/UserMenu.tsx, app/core/auth-options.ts, app/types/next-auth.d.ts, app/types/permissions.ts
=> feat(2962): add login event chart in analytics page

app/components/generic/table/SearchFilterExport.tsx, app/package-lock.json
=> feat(3296): enhance search input clear button behaviour

app/app/example/buttons/page.tsx, app/app/layout.tsx, app/app/mantine-theme.ts
=> feat(2759): add mantine color theme

app/package-lock.json, app/package.json
This reverts commit c2612c6e2969597ffc17d7eb270ba8b288c4b1da.
=> Revert "fix(deps): update dependency autoprefixer to v10.4.20"

cypress/integration/approve-request-test.feature, cypress/integration/create-request-private-test.feature, cypress/integration/delete-product-test.feature, cypress/integration/edit-request-private-test.feature, cypress/support/step_definitions/approve-request.ts, cypress/support/step_definitions/create-request.ts, cypress/support/step_definitions/delete-request.ts
Interim push to close two old tickets before the sprint ends. Polishing will go through with the next test.
=> feat(2399): implement code for BDD features, Create, Approve, Delete tests

docs/emou-workflow.md
=> feat(3502): add public eMOU workflow diagram

app/package-lock.json
Reverts bcgov/platform-services-registry#3509
=> Revert "fix(deps): update mantine monorepo to v7.12.1 - autoclosed"

localdev/README.md
This pull request updates the installation instructions to include steps for removing existing MongoDB and Mongosh installations before setting up the MongoDB container on a local machine. The changes ensure that the installation process is smooth and avoids conflicts with pre-existing installations.
=> docs(readme-modified): update installation instructions

Makefile, app/app/public-cloud/products/(product)/[licencePlate]/edit/page.tsx, app/app/public-cloud/requests/(request)/[id]/request/page.tsx, helm/main/Chart.yaml, helm/main/values-101ed4-dev.yaml, helm/main/values-101ed4-prod.yaml, helm/main/values-101ed4-test.yaml, helm/main/values.yaml
=> chore(3414): update billing eMOU status panel

app/app/api/billing/[idOrAccountCoding]/download/route.tsx, app/app/api/billing/[idOrAccountCoding]/exist/route.ts, app/app/api/billing/[idOrAccountCoding]/helpers.ts, app/app/api/billing/[idOrAccountCoding]/route.ts, app/package-lock.json, app/package.json
- Implement logic to determine whether the string received from the frontend is an Object ID or account code to avoid Prisma error on the ID field.
=> chore(3501): fix invalid ObjectID query issue

app/app/api/public-cloud/requests/[id]/sign-mou/route.ts, app/emails/_templates/public-cloud/BillingReviewerMou.tsx, app/jest.setup.js, app/package-lock.json, app/services/ches/public-cloud/email-handler.ts, app/services/keycloak/app-realm.ts
- send billing EMOU review request emails to billing reviewers retrieved from Keycloak after EA signs EMOU.
=> feat(3500): send billing EMOU review request emails

app/app/api/billing/[idOrAccountCoding]/download/BillingMou.tsx, app/app/private-cloud/products/(product)/[licencePlate]/edit/page.tsx, app/app/private-cloud/products/(product)/create/page.tsx, app/app/private-cloud/requests/(request)/[id]/decision/page.tsx, app/app/private-cloud/requests/(request)/[id]/original/page.tsx, app/app/private-cloud/requests/(request)/[id]/request/page.tsx, app/app/private-cloud/requests/(request)/[id]/summary/page.tsx, app/app/public-cloud/products/(product)/[licencePlate]/edit/page.tsx, app/app/public-cloud/products/(product)/create/page.tsx, app/app/public-cloud/requests/(request)/[id]/original/page.tsx, app/app/public-cloud/requests/(request)/[id]/page.tsx, app/app/public-cloud/requests/(request)/[id]/request/page.tsx, app/components/Landing.tsx, app/components/form/AccountCoding.tsx, app/components/form/AccountEnvironmentsPublic.tsx, app/components/form/Budget.tsx, app/components/form/CommonComponents.tsx, app/components/form/ExpenseAuthority.tsx, app/components/form/PageAccordion.tsx, app/components/form/ProjectDescriptionPrivate.tsx, app/components/form/ProjectDescriptionPublic.tsx, app/components/form/Quotas.tsx, app/components/form/TeamContacts.tsx, app/components/generic/AccordionLabel.tsx, app/components/table/TableBodyPrivateProducts.tsx, app/components/table/TableBodyPrivateRequests.tsx, app/components/table/TableBodyPublicProducts.tsx, app/components/table/TableBodyPublicRequests.tsx
=> feat(227): add accordion components

app/app/api/analytics/csv/quota/route.ts
- add a CSV endpoint to download the sum of the quotas
=> feat(analytics): add quota summary CSV endpoint

app/emails/private-cloud/AdminCreateRequest.tsx, app/emails/private-cloud/AdminDeleteRequest.tsx, app/emails/private-cloud/AdminRequest.tsx, app/emails/private-cloud/CreateRequest.tsx, app/emails/private-cloud/CreateRequestApproval.tsx, app/emails/private-cloud/DeleteCompletion.tsx, app/emails/private-cloud/DeleteRequest.tsx, app/emails/private-cloud/DeleteRequestApproval.tsx, app/emails/private-cloud/EditRequest.tsx, app/emails/private-cloud/EditRequestApproval.tsx, app/emails/private-cloud/EditRequestCompletion.tsx, app/emails/private-cloud/RequestProvisioned.tsx, app/emails/private-cloud/RequestRejection.tsx, app/emails/public-cloud/AdminCreateRequest.tsx, app/emails/public-cloud/AdminDeleteRequests.tsx, app/emails/public-cloud/AdminRequest.tsx, app/emails/public-cloud/CreateRequest.tsx, app/emails/public-cloud/DeleteCompletion.tsx, app/emails/public-cloud/DeleteRequest.tsx, app/emails/public-cloud/EditRequest.tsx, app/emails/public-cloud/ExpenseAuthority.tsx, app/emails/public-cloud/ExpenseAuthorityMou.tsx, app/emails/public-cloud/RequestApproval.tsx, app/emails/public-cloud/RequestProvisioned.tsx, app/emails/public-cloud/RequestRejection.tsx
=> chore: move react emails into separate directories

app/app/examples/ui/text-input/page.tsx, app/components/generic/input/FormTextInput.tsx, app/components/generic/input/HookFormTextInput.tsx, app/components/generic/select/HookFormMultiSelect.tsx, app/package-lock.json
=> feat(2827): add generic text input components

app/app/private-cloud/products/(product)/[licencePlate]/layout.tsx, app/app/private-cloud/products/(product)/create/page.tsx, app/app/private-cloud/requests/(request)/[id]/layout.tsx, app/app/public-cloud/products/(product)/[licencePlate]/layout.tsx, app/app/public-cloud/products/(product)/create/page.tsx, app/app/public-cloud/requests/(request)/[id]/layout.tsx, app/components/layouts/Header.tsx, app/emails/_templates/private-cloud/TeamEditRequestRejection.tsx, app/package-lock.json
=> feat(3361): display context in the application header

app/app/private-cloud/products/(product)/[licencePlate]/layout.tsx, app/app/private-cloud/products/(product)/create/page.tsx, app/app/private-cloud/requests/(request)/[id]/layout.tsx, app/app/public-cloud/products/(product)/[licencePlate]/layout.tsx, app/app/public-cloud/products/(product)/create/page.tsx, app/app/public-cloud/requests/(request)/[id]/layout.tsx, app/components/RequestStatusProgress.tsx, app/components/form/RequestBadge.tsx, app/components/generic/button/CopyableButton.tsx, app/components/table/TableBodyPrivateProducts.tsx, app/components/table/TableBodyPrivateRequests.tsx, app/components/table/TableBodyPublicProducts.tsx, app/components/table/TableBodyPublicRequests.tsx, app/constants/emails.ts, app/constants/index.ts, app/request-actions/private-cloud/edit-request.ts, app/services/ches/private-cloud/index.ts, app/services/ches/public-cloud/emails.ts
=> feat(3925): use progress design in request list pages

app/components/RequestStatusProgress.tsx, app/components/UserCard.tsx, app/components/billing/PublicCloudBillingInfo.tsx, app/components/form/ProductBadge.tsx, app/components/generic/input/AutoResizeTextArea.tsx, app/emails/_templates/public-cloud/BillingReviewerMou.tsx, app/helpers/mock-resources/private-cloud-request.ts, app/helpers/mock-resources/public-cloud-request.ts, app/prisma/schema.prisma, app/request-actions/private-cloud/decision-request.ts, app/request-actions/public-cloud/decision-request.ts, app/services/db/includes.ts, app/types/private-cloud.ts, app/types/public-cloud.ts, helm/main/values-101ed4-prod.yaml
=> chore: enhance minor UI elements

app/app/api/keycloak/api-accounts/team/[id]/route.ts, app/app/api/keycloak/api-accounts/team/_operations/create.ts, app/app/api/keycloak/api-accounts/team/_operations/update.ts, app/app/api/keycloak/api-accounts/team/route.ts, app/app/api/tasks/assigned/route.ts, app/app/team-api-accounts/createAccountModal.tsx, app/app/team-api-accounts/manageAccountModal.tsx, app/app/team-api-accounts/page.tsx, app/app/team-api-accounts/viewAccountModal.tsx, app/components/generic/tabs/BasicTabs.tsx, app/components/layouts/Header.tsx, app/components/layouts/SideTasks.tsx, app/services/backend/keycloak.ts, app/services/backend/tasks.ts, app/validation-schemas/api-accounts.ts
1. add `name` field into `team API tokens`.
2. add `description` into `assigned tasks`.
3. add `loader` during loading session into in layout header right section.
=> chore(4018): enhance minor UI elements

.pre-commit-config.yaml, cypress/e2e/create-test.cy.ts, cypress/integration/edit-request-private-test.feature, cypress/support/step_definitions/common.ts
Tweak Edit Request Private Cloud test to run in GitHub actions and new UI
=> feat(3812): tweak edit private cloud test to run in github actions and new UI

.github/actions/scan-docker-image/action.yml, .github/workflows/deploy-dev.yml, .github/workflows/deploy-test.yml
=> chore(2692): enhance the workflow

cypress/e2e/create-test.cy.ts, cypress/integration/create-request-private-test.feature, cypress/integration/create-request-public-test.feature, cypress/integration/edit-request-private-test.feature
Change E2E tests to correspond to new modal component
=> feat(4121): change e2e tests to correspond to new modal component

app/app/api/users/search/route.ts, app/components/modal/userPicker.tsx, app/components/users/UserAutocomplete.tsx, app/package-lock.json, app/services/backend/users.ts, app/services/db/user.ts, localdev/keycloak-provision/src/main.ts
=> feat(4156): add user search reusable picker modal

app/components/form/ProjectDescriptionPrivate.tsx, app/components/form/Quotas.tsx, app/components/generic/select/HookFormSingleSelect.tsx
- it resolves the issue binding the value of generic select-options element by Next.js 15 upgrade.
=> fix(4165): replace generic select with dropdown for cluster

app/components/generic/select/FormMultiSelect.tsx
=> feat(4221): use different view for disabled multi-select

app/app/api/private-cloud/nats.test.ts, app/app/api/private-cloud/products/_operations/update.ts, app/app/api/public-cloud/products/_operations/update.ts, app/constants/private-cloud.ts, app/services/nats/private-cloud/index.ts
=> feat(4215): update private cloud Nats message

app/components/private-cloud/sections/AdditionalTeamMembers.tsx, app/components/public-cloud/sections/AdditionalTeamMembers.tsx, app/constants/private-cloud.ts, app/services/nats/private-cloud/index.ts
- it includes a partial revert of the PR: https://github.com/bcgov/platform-services-registry/pull/4253/files
=> chore(4215): send distinct NATs messages based on the environment

cypress/integration/2. create-request-public-test.feature, cypress/integration/4. approve-requests-private.feature, cypress/integration/6. edit-request-public-test.feature, cypress/support/step_definitions/common.ts
Redone edit request for public cloud with universal steps, and added a couple of fixes
=> e2e(4125): edit request for public cloud and couple of fixes

.tool-versions
Reverts bcgov/platform-services-registry#4580
=> Revert "chore(deps): update dependency pnpm to v9.15.2"

app/app/events/all/TableBody.tsx, app/services/backend/events.ts, app/services/db/event.ts
=> feat(3973): add data column to event table

localdev/keycloak-provision/main.ts, localdev/mock-users.json
Add multiple roles provisioning in localdev keycloak and two example users
=> feat(4100): add multiple roles provisioning in localdev keycloak

app/app/layout.tsx, app/app/not-found.tsx, app/components/generic/tabs/BasicTabs.tsx, app/components/layouts/Header.tsx
- redirect 404 page to home page
- sticky header
- update tab style
- add more spaces between body and footer
=> feat(4749): redirect 404 page to home page

app/app/events/all/page.tsx, app/app/tasks/all/FilterPanel.tsx, app/app/tasks/all/TableBody.tsx, app/app/tasks/all/page.tsx, app/app/tasks/all/state.ts, app/app/users/all/TableBody.tsx, app/app/users/all/page.tsx, app/components/generic/KeyValueTable.tsx, app/components/users/UserProfile.tsx, app/constants/index.ts, app/constants/task.ts, app/services/db/task.ts, app/services/db/tasks/review-private-cloud-request.ts, app/services/db/tasks/review-public-cloud-request.ts, app/types/task.ts, app/validation-schemas/task.ts
=> feat(4853): enhance Tasks admin page

app/app/public-cloud/products/(product)/create/page.tsx, app/components/form/Budget.tsx, app/components/generic/input/FormDollarInput.tsx, app/validation-schemas/public-cloud.ts
https://app.zenhub.com/workspaces/app-dev-team-646fdb4400ed8c0021aceeb4/issues/gh/bcgov/platform-services-registry/4973
=> feat(4973): update Public Cloud product page based on provider

.github/workflows/dispatch-deploy.yml, .github/workflows/release-tag-changelog.yml
output running locally 
```
Last tag: v0.47.0
Commit messages since last tag:
Merge pull request #5152 from bcgov/changelog/0.47.0
chore(release): release candidate v0.47.0
Merge pull request #5153 from bcgov/chore/4927
feat(4927): add reusable TooltipTableHeader component
chore(4927): change last active tooltop text
chore(4927): remove redundant import
feat(4927): add reusable TooltipTableHeader component
Bump type: minor
Determined next version: v0.48.0
```
=> feat(5059): update deploy dispatch workflow for automated versioning

helm/_app/templates/deployment-maintenance.yaml, helm/_app/values.yaml, helm/main/templates/mongodb-backup.yaml, helm/main/values.yaml
- update maintenance Helm chart
- set database expiry day flag
=> chore(4966): update the maintenance Helm chart

app/components/private-cloud/monthly-cost/monthly-cost-chart-data.tsx, app/helpers/pdfs/monthly-cost/index.tsx
=> chore(5383): adjust font sizes for PDF download

app/app/private-cloud/products/(product)/[licencePlate]/costs/Monthly.tsx, app/app/private-cloud/products/(product)/[licencePlate]/costs/Quarterly.tsx, app/app/private-cloud/products/(product)/[licencePlate]/costs/Yearly.tsx, app/app/private-cloud/products/(product)/[licencePlate]/costs/page.tsx, app/app/private-cloud/products/(product)/[licencePlate]/layout.tsx, app/components/private-cloud/monthly-cost/MonthlyCostTable.tsx, app/components/private-cloud/quarterly-cost/QuarterlyCostTable.tsx, app/helpers/pdfs/monthly-cost/index.tsx, app/helpers/pdfs/quarterly-cost/index.tsx
=> feat(5648): consolidate private cloud product cost pages

helm/tools/Makefile, helm/tools/dags/acs_dev.py, helm/tools/dags/acs_prod.py, helm/tools/dags/acs_test.py, helm/tools/dags/airflow_failure_test.py, helm/tools/dags/mailchimp_subscription_dev.py, helm/tools/dags/mailchimp_subscription_prod.py, helm/tools/dags/mailchimp_subscription_test.py, helm/tools/dags/provisioner_prod.py, helm/tools/dags/provisioner_test.py, helm/tools/dags/sonarscan_dev.py, helm/tools/dags/sonarscan_prod.py, helm/tools/dags/sonarscan_test.py, helm/tools/dags/sync_db_with_azure_ad_dev.py, helm/tools/dags/sync_db_with_azure_ad_prod.py, helm/tools/dags/sync_db_with_azure_ad_test.py, helm/tools/dags/temporary_products_deletion_dev.py, helm/tools/dags/temporary_products_deletion_prod.py, helm/tools/dags/temporary_products_deletion_test.py, helm/tools/dags/temporary_products_notification_dev.py, helm/tools/dags/temporary_products_notification_prod.py, helm/tools/dags/temporary_products_notification_test.py, helm/tools/dags/zapscan_dev.py, helm/tools/dags/zapscan_prod.py, helm/tools/dags/zapscan_test.py, helm/tools/templates/job.yaml, helm/tools/values.yaml, tools/airflow/Dockerfile
=> refactor(5746): update Airflow codebase for compatibility with v3

app/app/analytics/general/page.tsx, app/app/analytics/private-cloud/ActiveProducts.tsx, app/app/analytics/private-cloud/AllRequests.tsx, app/app/analytics/private-cloud/ContactChangeRequests.tsx, app/app/analytics/private-cloud/MinistryDistribution.tsx, app/app/analytics/private-cloud/QuotaRequests.tsx, app/app/analytics/private-cloud/RequestsDecisionTime.tsx, app/app/analytics/public-cloud/ActiveProducts.tsx, app/app/analytics/public-cloud/AllRequests.tsx, app/app/analytics/public-cloud/ContactChangeRequests.tsx, app/app/analytics/public-cloud/MinistryDistribution.tsx, app/app/analytics/public-cloud/RequestsDecisionTime.tsx, app/components/analytics/BarChartCard.tsx, app/components/analytics/LineChartCard.tsx, app/components/analytics/MultipleDoughnutChartCard.tsx, app/components/generic/charts/BarChart.tsx, app/components/generic/charts/DoughnutChart.tsx, app/components/generic/charts/LineChart.tsx
=> feat(5736): encapsulate shared chart logic into common components

helm/tools/values.yaml
=> feat(5782): add minio deployment via helm

helm/tools/values-101ed4-tools.yaml, helm/tools/values.yaml
=> feat(5758): add remote logging support for Airflow tasks

app/app/team-api-accounts/page.tsx, app/components/generic/data-table/DataTable.tsx
=> feat(5856): replace team api account table with cc table

helm/tools/Chart.lock, helm/tools/Chart.yaml, helm/tools/values-101ed4-tools.yaml, helm/tools/values.yaml
Deployment of mongodb in tools namespace via Helm
=> feat(4778): deployment of mongodb in tools namespace

app/pnpm-lock.yaml
Reverts bcgov/platform-services-registry#6070
=> Revert "fix(deps): update dependency react-email to v4.2.1"

app/pnpm-lock.yaml
Reverts bcgov/platform-services-registry#6137
=> Revert "fix(deps): update dependency @react-email/preview-server to v4.2.4"

app/services/db/members-history.ts
=> chore(6088): display role change if user has more than one role
