bcgov/platform-services-registry

- api/src/controllers/namespace.ts
- api/src/controllers/profile.ts
- api/src/db/index.ts
- api/src/db/model/model.ts
- api/src/libs/shared.ts
Each model was creating its own pool. As more models are added this will quickly and unnecessarily exhaust PostgreSQL available connections. This fixes the problem by creating a shared pool (the way it should be done).
Fixes #30
> Fix pg pool usage

- web/src/components/authbutton.tsx
- limiting authentication methods through keycloak to only use IDIR
- adding TODO note so we can allow GitHub again after we implement better access control
Fixes #81
> Only allow users with IDIR to authenticate against the registry

- README.md
- api/openshift/templates/deploy.yaml
- api/openshift/templates/secret.yaml
- openshift/templates/patroni-build.yaml
- openshift/templates/patroni-deploy.yaml
- openshift/templates/patroni-pre-req.yaml
- Updated build/deploy instructions in the README.md to add steps to build/deploy a patroni service. 
>no requirement for a build, but it's there for convenience.  Simply need to change the IMAGE_STREAM_xxx parameters to leverage the patroni image you want.
- Updates made to remove postgresql secrets, pvc, service, deployment from existing templates
- Updated env variables in api deployment to use new patroni secrets
- Integrated deployment testing - Patroni build/deploy test out fine, but I'm currently unable to deploy the rest of the app without additional assistance.
- create a build/deploy/config for the backup-container
> Replace postgresql with Patroni service

- web/src/AppRouter.tsx
- web/src/__tests__/__snapshots__/form.test.tsx.snap
- web/src/components/DropdownMenu.tsx
- web/src/components/DropdownMenuItem.tsx
- web/src/components/Layout.tsx
- web/src/components/SubFormPO.tsx
- web/src/components/SubFormProject.tsx
- web/src/components/SubFormTC.tsx
- web/src/components/footer.tsx
- web/src/components/header.tsx
- web/src/constants.ts
- web/src/index.tsx
- web/src/types.tsx
- web/src/views/form.tsx
- fix related to "a new openshift project set" request form
- making it more obvious the request button is clickable
- redirecting users after a successful submission back to the dashboard where they will be seeing their newly requested projects when the dashboard view feature gets complete
- letting users know their submission is currently being processed (sequential API calls in the background) by bringing up a backdrop
- fix related to dropdown menus
- modifying the desktop dropdown menu from "create" button so it will close after a menu item is clicked
- modifying the mobile dropdown menu so it will close after a menu item is clicked
- fix related to React paths
- changing the path name "namespaces/create" to "projects/create" to be consistent with the view form
- adding the home path …
> Bug fixing and enhancement around the form for creating new project set

- web/package-lock.json
- web/package.json
- web/src/__tests__/__snapshots__/form.test.tsx.snap
- web/src/__tests__/form.test.tsx
- web/src/components/SubFormPO.tsx
- web/src/utils/TokenDecoder.tsx
- web/src/utils/useDecoder.tsx
Resolves issue #75 , to encourage PO's to initialize project provisioning, the project creation form now pre-populates the PO first name, last name and email from information contained within the JWT.
> Pre Populate PO information in Project Registry

- api/src/db/model/contact.ts
Rectifies Issue #129 . As KeyCloak SSO requires the stored userId to be entirely lowercase, it is necessary to convert user input GitHub id's to lowercase to avoid configuration issues.﻿
> Convert github id to lowercase string

- web/src/__tests__/__snapshots__/form.test.tsx.snap
- web/src/components/SubFormPO.tsx
As a user, partners require ability to update both PO and TC to meet the workflow of different ministries.
This PR enables the ability for users to update the information within the pre-populated PO fields.
Fixes #186
> Enable edit capability for pre-populated PO form

- api/src/db/model/profile.ts
It was recognised that trailing whitespaces included in the Project name input resulted in an unnecessary underscore being appended to the project repo during provisioning. 
This fix ensures that all namespaces do not have leading or trailing whitespaces in their name.﻿
> Trim leading and trailing whitespace from project name

- api/__tests__/__snapshots__/messaging.spec.ts.snap
- api/__tests__/messaging.spec.ts
- api/src/libs/messaging.ts
- api/templates/provisioning-request-done.txt
- api/templates/provisioning-request-received.txt
Users reported concerns regarding a lack of project specific information within the provisioning email. This PR ensures provisioning emails contain the project name, and PO and TC contact details.
This PR includes: 
Fixes #185
> Update namespace provisioning email

- web/src/__tests__/__snapshots__/ProfileCard.test.tsx.snap
- web/src/components/ProfileCard.tsx
- web/src/components/SubFormPO.tsx
- web/src/components/SubFormProject.tsx
- web/src/components/SubFormTC.tsx
- web/src/components/UI/newLineText.tsx
- web/src/utils/getValidator.tsx
- providing a fix so the return key is accepted by profile form submission - description field
- updating the dashboard profile card so description can read return key and render new line
- updating snapshots
- renaming useValidator to getValidator to follow the naming conventions where useXXX is only for react state / hooks related stuff
Fixes #166
> Project Registry Description field 'Invalid Format' when return key is used

- api/src/libs/messaging.ts
It was discovered if the PO and TC had the same email address, the provisioning email would show the TC Email as `undefined`. This PR checks if the PO and TC have the same address and provisioning the namespace email accordingly.
Fixes #203
> Bugfix: ensure TCEmail is not undefined

- web/src/components/ProfileEditableProject.tsx
To protect current description fields from invalid characters, the description box is no longer editable.
> Disable description editing

- web/src/utils/getValidator.tsx
To avoid an issue discovered in ArgoCD from unescaped double quotes, they have been temporarily disabled until a proper solution can be implemented.
> Remove double quote from descriptions

- api/__tests__/fulfillment.spec.ts
- api/__tests__/namespace.spec.ts
- api/doc/api.yaml
- api/public/doc/api/index.html
- api/src/constants.ts
- api/src/controllers/namespace.ts
- api/src/controllers/provision.ts
- api/src/db/model/cluster.ts
- api/src/db/model/contact.ts
- api/src/db/model/ministry.ts
- api/src/db/model/model.ts
- api/src/db/model/namespace.ts
- api/src/db/model/profile.ts
- api/src/db/model/request.ts
- api/src/db/model/userprofile.ts
- api/src/libs/fulfillment.ts
- api/src/libs/quota-editing.ts
- ts linting
- refactor work around quota edit
- refactor work so there are reusable components that aren't just specific to quota edit but all edits
- refactor work so clusterName is read as optional request param as bot is currently passing to provision endpoint
Fixes #222 
> Current quote edit feature will work well with future profile edits

- api/src/libs/fulfillment.ts
- web/src/utils/getValidator.tsx
- on the api side, stringify nats message before sending
- on the web side, allow double quote in profile description
Some notes:
It turns out that the double quotes have been properly escaped when they are collected from the web and stored in DB.
It's just when we send structured data through nats, without JSON.stringify, they won't be escaped properly.
Since the ansible side has already got the step to parse the nats msg, the solution is to JSON.stringify it first.
Fixes #213
> Bugfix for profile description containing unescaped quote in it

- api/__tests__/__snapshots__/sync.spec.ts.snap
- api/__tests__/sync.spec.ts
- api/__tests__/utils.spec.ts
- api/src/controllers/sync.ts
- api/src/libs/fulfillment.ts
- api/src/libs/utils.ts
- replace double quote character with whitespace when sending nats / json message
- revert back to serving json oppose to string
- update unit tests
The proposed changes should resolve the following issue:
Ansible json decodes the json message when converting it to a var which would unescape the " and then it wouldn't be valid yaml for OpenShift.
Fixes #213
> Bugfix to address the unescaped double quote issue in manifest yaml

- api/package-lock.json
- api/package.json
- fix the dependabot alert node-notifier >=8.0.1
To ensure that functionalities and behaviours are working as expected after the libraries update, the code was tested locally by running unit tests for registry api portion using jest, as that's where the node-notifier and its parent library are being used.
Due to dependency and sub-dependency updates:
> Manually resolve dependabot alert issue on node-notifier

- web/src/utils/getProfileStatus.tsx
- web/src/views/ProfileEditable.tsx
The initial method for determining if there was a pending edit request involved too much duplication. This is a simple refactor to improve future use.
> Refactor pendingEditRequest

- web/src/__tests__/__snapshots__/ProfileCreate.test.tsx.snap
- web/src/components/profileCreate/CreateFormProject.tsx
Adjustments to the migration status note to include clarifying details of OCP 3.11 namespace name.
Fixes #282
> Update description of  migration status note

- web/src/AppRouter.tsx
- web/src/__tests__/ContactCard.test.tsx
- web/src/__tests__/ProjectCard.test.tsx
- web/src/components/common/layout/Header.tsx
- web/src/components/profileEdit/ContactCard.tsx
- web/src/components/profileEdit/ContactCardEdit.tsx
- web/src/components/profileEdit/ProjectCard.tsx
- web/src/components/profileEdit/ProjectCardEdit.tsx
- web/src/components/profileEdit/QuotaCard.tsx
- web/src/components/profileEdit/QuotaCardEdit.tsx
- web/src/constants.ts
- web/src/contexts/commonStateContext.tsx
- web/src/hooks/useCommonState.tsx
- web/src/layouts/Layout.tsx
- web/src/types.tsx
- web/src/utils/AppRoute.tsx
- web/src/utils/PrivateRoute.tsx
- web/src/utils/getProfileStatus.tsx
- web/src/utils/transformDataHelper.tsx
- web/src/views/Dashboard.tsx
- web/src/views/ProfileCreate.tsx
- web/src/views/ProfileEdit.tsx
Fixes #276 
Due to refactor volume:
> Clean up frontend state mgmt including ProfileEdit component

- db/flyway.Dockerfile
The pre-hook pod container fails to start with flyway v 7.4.0. Upgrading the version seems to have resolved this issue.
> Update flyway docker build

- api/src/controllers/project-profile.ts
This is a fix that enables users to update the migrating application licenseplate information from the project edit page.
> Update updateProjectProfile to include migratingLicenseplate

- web/src/components/profileEdit/ProjectCardEdit.tsx
This PR was necessary to disable the project name field within the edit capability﻿
> Disable Project Name input field

- web/src/constants.ts
This is to add the following additional attributes to the csv extract:
- ocp3 migration status
- license plate
Fixes #325
> Add ocp3 migration status to csv extract

- db/sql/V1.11__update_large_quota_values.sql
This PR fixes the discovery that the current CPU_request and CPU_limit size for a 'large' tshirt size is double the expected value. According to [here](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/openshift4-rollout/254), the values should be 16, and 32 respectively.
Fixes #375 
**This PR will require a sync from the provisioner system to take full effect**
> Update large cpu_request and cpu_limits to correct value

- db/flyway.Dockerfile
Due to the unauthenticated docker pull issue, this temporary fix is to avoid using docker registry and instead use redhat registry.
> Provide a temporary fix to build flyway image

- web/src/utils/Wizard.tsx
This PR fixes a bug that resulted in the Request button within the project create process not switching back to Next if a user navigated to a previous card after reaching the final step. ﻿
> Set LastPage state false if user hits previous on last card

- api/src/controllers/provision.ts
This PR updates the cluster key in the provisionerCallbackHandler to match what GitHub is actually sending (clusterName).
> Update provisionCallbackHandler body to unpack clusterName

- api/__tests__/__snapshots__/project-profile.spec.ts.snap
- api/__tests__/project-profile.spec.ts
- api/src/controllers/project-profile.ts
- web/src/components/profileEdit/ProjectCardEdit.tsx
This PR introduces the ability to edit Project display names within the Registry / OpenShift. 
Fixes #237
> Enable users to edit profile names

- api/__tests__/__snapshots__/fulfillment.spec.ts.snap
- api/__tests__/fulfillment.spec.ts
- api/src/db/model/namespace.ts
- api/src/libs/bot-message.ts
- api/src/libs/fulfillment.ts
- api/src/types.ts
- web/.eslintrc
- web/src/views/Dashboard.tsx
As noted in [ticket #1274](https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/1274) the JSON message between the Registry and the Provisioner required some refactoring.
This PR refactors the namespace and contact logic to align with the new format. 
Note: The NATS interface has been documented in snake case instead of the conventional camel case used throughout the Registry. I figured this would avoid potential incidents in the future of expected output vs modifying the JSON payload from camelCase to snake_case immediately before transmission. I am open to thoughts regarding this design decision though.
> Refactored NATS context message into snake case and v2 format

- db/flyway.Dockerfile
flyway master build uses UBI image "registry.access.redhat.com/ubi8/openjdk-11", which was just updated, causing the build to break.  The Dockerfile (flyway.Dockerfile in this case) has been updated to accommodate the change.
> Fix flyway Dockerfile

- db/sql/V2.4__remove_unique_profile_name_constraint.sql
Due to the revised gitops storage organization, teams can now edit project names as they wish. This no longer requires project names to be unique as a result. This PR removes the unique profile name constraint from the database.
> Remove unique profile name constraint

- api/src/controllers/sync.ts
The sync flow happened to bypass a JSON.stringify step necessary for the buildContext function to run. This PR includes a check for Edit Type and parses the object if it is a project profile.
> Update sync pending project details fetch

- web/src/components/profileEdit/ContactCardEdit.tsx
When we updated the project creation fields to auto capitalize the fields, the email and github ID fields were missed in the Contact Edit page. This PR updates these fields to remove this formatting.
> Remove forced capitalization of email and githubID

- api/src/controllers/request.ts
When a project request gets rejected in the Dashboard approvals, the `requiresHumanAction` flag never gets marked as negative. By moving this functionality outside of the `if (type === HumanActionType.Approve)` check ensures that the field is updated for all human actions.
> Move receivedHumanAction earlier so it is captured during rejection

- api/src/controllers/sync.ts
The sync flow happened to bypass a JSON.stringify step necessary for the buildContext function to run. This PR includes a check for Edit Type and parses the object if it is a contact edit.
This was first discovered in PR #447
> Update contact edit sync context parse

- web/src/views/ProfileEdit.tsx
Ticket: https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcgov/platform-services-registry/403
remove the logic to hide the ‘edit’ button if pending edits, that way users can still get to the edit page even if there is a pending edit.
> Disable edit logic for Quota edit

- .github/workflows/dev-api.yml
- .github/workflows/dev-db.yml
- .github/workflows/dev-web.yml
- .github/workflows/promote_to_test-v2.yml
I've added a concurrency check to workflows that build images in order to prevent errors from simultaneous build jobs.  The value of the concurrency field is the image name, such as `platsrv-registry-api`, and is set on a per-job (build) basis.  A second workflow run will show "pending" until the first run is complete.  This allows all runs to be processed, instead of cancelling the second one, which may have been initiated by a second commit.
> Workflow concurrency

- api/__tests__/__snapshots__/fulfillment.spec.ts.snap
- api/src/libs/fulfillment.ts
- api/src/types.ts
This PR introduces the Ministry ID into the NATS Context. Which is necessary for the Warden Operator and ArgoCD Shared so we don’t have to manage the list of namespaces attached to an AppProject manually.
> Add ministry id to NATS context message

- api/src/libs/profile.ts
- db/sql/V4.3__downgrade_klab_quota.sql
- web/src/utils/transformDataHelper.tsx
https://app.zenhub.com/workspaces/platform-experience-5bb7c5ab4b5806bc2beb9d15/issues/bcdevops/developer-experience/2205
For testing purposes, we first downgrade tool namespace quota in klab/clab first
This pr also solves a duplicate key problem where sometimes a project has the same first and second Technical lead.
> klab tool quota downgrade

- web/src/components/dashboard/PSRDocumentationLink.tsx
- web/src/views/Dashboard.tsx
From the task description:
"I could not find any links or references to any (Help or About) documentation that describes this applications purpose, functions, scope. Without this kind of information I find it harder to use the application and provide meaningful feedback." 
I just added a link to the top of the dashboard, "Git documentation for Platform Services Registry and a link to report issues can be found [here](http://localhost:8101/https://github.com/bcgov/platform-services-registry)"
I created a new React component "PSRDocumentationLink" for this, and added it on the dashboard.
> Documentation link

- app/api/private-cloud/requests/route.ts
- prisma/schema.prisma
- prisma/seed.ts
I believe it could happen with a `prisma`'s nature of auto-generating types by running `prisma generate`.
So that when `schema.prisma` is updated and forgets to run the command again, it would be difficult to pick up the type errors in the local environments.
> chore: fix build errors

- .github/workflows/test.yml
- localdev/docker-compose-ci.yml
- it will reduce the time to test integration tests in CI by using deployed container images.
> chore: use published localdev images in test

- middleware.ts
- This tool might helps but let's take another look later: https://www.npmjs.com/package/@next-safe/middleware
> chore: enable unsafe-inline CSP for static HTML files

- app/api/private-cloud/create/route.ts
- helpers/apiErrorHandler.ts
- since the api endpoints are captured errors and using `try.. catch` can be duplicated in multiple places, let's have a global handler to capture the responses and errors.
> feat: add global api response handler

- app/api/auth/options.ts
- types/next-auth.d.ts
- move common session context in higher level
```
{
...
roles: ['admin', 'ministry-citz-admin'],
isAdmin: true,
ministries: { admin: ['citz'], readonly: [] },
}
```
> feat: enhance session context in higher level

- components/modal/CreatePrivateCloud.tsx
- components/modal/CreatePublicCloud.tsx
- emails/templates/private-cloud/RequestRejection.tsx
Fixed modal for PrivateCloudModal and added the link for `Onboarding Guide`
Added link for `Public Cloud Services Shared Responsibility` in PublicCloudModal
Fixed wording for rejection email
> fix: wording on privatecloud modal and links in modals

- helm/secdash/.helmignore
- helm/secdash/Chart.lock
- helm/secdash/Chart.yaml
- helm/secdash/Makefile
- helm/secdash/README.md
- helm/secdash/dags/test.py
- helm/secdash/example-job.yaml
- helm/secdash/templates/_helpers.tpl
- helm/secdash/templates/configmap.yaml
- helm/secdash/templates/job.yaml
- helm/secdash/templates/networkpolicy.yaml
- helm/secdash/templates/pvc.yaml
- helm/secdash/templates/route.yaml
- helm/secdash/templates/secrets/postgresql.yaml
- helm/secdash/templates/secrets/webserver.yaml
- helm/secdash/values-101ed4-tools.yaml
- helm/secdash/values.yaml
The primary Helm chart for deployment relies on two subordinate Helm charts: `Airflow` and `PostgreSql`. Given that `Airflow` is dependent on `PostgreSql`, the initial deployment sequence involves deploying `PostgreSql` before initiating the deployment of `Airflow` instances.
1. In the Helm values file specific to the environment (e.g., `values-101ed4-tools.yaml`), set the value of `airflow.enabled` to `false`.
2. Deploy the `PostgreSQL` database:
```sh
make upgrade NAMESPACE=101ed4-tools
```
3. Once the database deployment is complete, proceed to deploy `Airflow`:
```sh
make upgrade NAMESPACE=101ed4-tools
```
- Prior to the deployment of `Airflow`, a [job]('./templates/templates/job.yaml) runs to `synchronize the dags`. Due to the upload mechanism using a [config …
> feat: add helm chart for airflow deployment

- .env.localdev
- app/api/auth/options.ts
- helm/main/templates/mongodb-backup.yaml
- helm/main/values-101ed4-dev.yaml
- localdev/README.md
- localdev/docker-compose.yml
- terraform/keycloak/.terraform.lock.hcl
- terraform/keycloak/config.tf
- terraform/keycloak/dev/config.tf
- terraform/keycloak/dev/main.tf
- terraform/keycloak/dev/ministry-roles.tf
- terraform/keycloak/dev/roles.tf
- terraform/keycloak/dev/variables.tf
- terraform/keycloak/main.tf
- terraform/keycloak/prod/config.tf
- terraform/keycloak/prod/main.tf
- terraform/keycloak/prod/ministry-roles.tf
- terraform/keycloak/prod/roles.tf
- terraform/keycloak/prod/variables.tf
- terraform/keycloak/test/config.tf
- terraform/keycloak/test/main.tf
- terraform/keycloak/test/ministry-roles.tf
- terraform/keycloak/test/roles.tf
- terraform/keycloak/test/variables.tf
- terraform/keycloak/variables.tf
let's create new KC clients to avoid any conflicts with the current registry's usage:
please update `AUTH_RESOURCE` to `pltsvc` and `AUTH_SECRET` from new Keycloak clients respectfully:
- dev: https://dev.loginproxy.gov.bc.ca/auth/admin/platform-services/console/#/realms/platform-services/clients/13514f3c-0d09-4ecf-860f-d34cbcebd7b2/credentials
- test: https://test.loginproxy.gov.bc.ca/auth/admin/platform-services/console/#/realms/platform-services/clients/513cb1b1-25da-4095-8ed9-1afa59ca716e/credentials
- dev: https://loginproxy.gov.bc.ca/auth/admin/platform-services/console/#/realms/platform-services/clients/624b2484-cb5b-4d1e-9a7f-87558a01cefd/credentials
> feat: new kc clients for new UI

- components/form/Budget.tsx
- components/form/BudgetInput.tsx
- schema.ts
- Can now add numbers that contain decimals with up to 2 following digits i.e `50.11`,`50.1`,`50.`
- Floating point precision is now fixed
- Now handling errors properly when adding a decimal value that are more than 2 digits.
> fix: add decimal values in budget field

- components/form/Quotas.tsx
- Added link to the Quota Increase Request Process documentation page
- Bolding now includes "not" for better clarity
- Addition of a Comma and Conjunction:
Original: 
> "All quota increase requests require Platform Services Team's approval must have supporting information as per the Quota Increase Request Process."
Changed: 
> "All quota increase requests require Platform Services Team’s approval, and must have supporting information as per the Quota Increase Request Process."
Change Explained: A comma and the conjunction "and" were added after "approval". This change improves the sentence structure, making it clearer and grammatically correct.
- Change in the Structure of the Second Sentence:
Original: 
> "The Quota Requests without supporting information will not be processed." …
> fix: added link to quota increase process

- emails/_templates/public-cloud/Provisioned.tsx
link for public product email RC channel changed to #aws-tenant-requests
> Replace public cloud email RC channel link

- app/api/private-cloud/decision/[licencePlate]/route.ts
- app/api/private-cloud/provision/[licencePlate]/route.ts
- components/modal/Comment.tsx
- docs/email-scenarios-private-cloud.md
- emails/PrivateCloudAdminRequest.tsx
- emails/PrivateCloudRequestApproval.tsx
- emails/PrivateCloudRequestRejection.tsx
- emails/_components/Comment.tsx
- emails/_components/Edit/QuotaChanges.tsx
- emails/_templates/private-cloud/AdminEditRequest.tsx
- emails/_templates/private-cloud/RequestApproval.tsx
- emails/_templates/private-cloud/RequestRejection.tsx
- services/ches/private-cloud/email-handler.ts
1. Fixed subject line for admin email
2. fixed punctuation in edit request email
3. admins now see comments from user for an edit request
4. added logic for sending the correct email based on type of request (edit vs create)
5. updated the documentation for scenario 2 approval and rejection emails
6. rejection email now shows what was rejected (what quota was rejected)
> Fix: Scenario #2 for Email refactoring/improving according to docs (Private Cloud)

- app/components/table/TableBodyPrivateProducts.tsx
- app/components/table/TableBodyPrivateRequests.tsx
- app/components/table/TableBodyPublicProducts.tsx
- app/components/table/TableBodyPublicRequests.tsx
- app/components/table/TruncatedTooltip.tsx
- app/components/table/styles.css
> fix(3093): add word wrap and character limit to description tool tips

- app/components/buttons/DeleteButton.tsx
- app/components/modal/PrivateCloudDelete.tsx
- app/components/modal/PublicCloudDelete.tsx
- app/package-lock.json
Private Cloud Registry
- Modified the warning text `This operation cannot be undone` in the confirm deletion UI modal, changing its text to red and bolding it's font 
- Changing the Delete Buttons on the Private and Public Registry to red, animating and adding on-hover effect.
Public Cloud Registry
- Modified the warning text `This operation cannot be undone` in the confirm deletion UI modal, changing its text to red and bolding it's font
- Changing the Delete Buttons on the Private and Public Registry to red, animating and adding on-hover effect. 
- Replacing the info link: `this will permanently delete your product` with the link: https://digital.gov.bc.ca/cloud/services/public/intro/#closure
> fix(3157): update UI delete confirmation modal

- app/components/modal/AddUser.tsx
- app/core/auth-options.ts
- app/emails/_components/Params.ts
- app/package-lock.json
- app/prisma/schema.prisma
- app/queries/users.ts
- app/services/db/user.ts
- app/services/msgraph/index.ts
- app/services/nats/public-cloud/index.ts
- app/types/user.ts
- include MS AD user object ID into public cloud NATS messages as public cloud team wants to use it for their provisioner.
> feat(3576): include MS AD user object ID into public cloud NATS

- app/app/private-cloud/products/(product)/[licencePlate]/comments/page.tsx
- app/app/private-cloud/requests/(request)/[id]/comments/page.tsx
- app/components/table/EmptySearch.tsx
> feat(3663): add graphic for when there are no comments to display

- .github/workflows/cypress-e2e-test.yaml
- cypress/_tmp/edit-request-private-test.feature
- cypress/integration/create-request-public-test.feature
feat(3814): tweak public cloud create test to run in github actions
Adding timeouts in Public Cloud Create Test,
Updating text to find the checkbox in 'All Set' modal window,
Update the timeout and delete call to docker-compose-ci in workflow e2e tests file.
> feat(3814): tweak public cloud create test to run in github actions

- app/components/generic/Label.tsx
- app/components/generic/select/FormMultiSelect.tsx
- app/components/generic/select/FormSingleSelect.tsx
- app/package-lock.json
generic components
- Label
- FormSingleSelect
- FormMultiSelect
> feat(3165): add label and select generic components

- .github/workflows/cypress-e2e-test.yaml
Narrow down the services running in E2E GitHub action to only needed services.
Run only keycloak, keycloak-provision, postgres, m365mock, mongodb, nats and nats-provision services when running E2E tests.
Needed because other services take computational time and are not needed in the run.
Also if they break they block testing.
> chore(4337): narrow down/specify services needed for e2e github action

- app/app/private-cloud/products/(product)/[licencePlate]/usage/MetricsTable.tsx
- app/app/private-cloud/products/(product)/[licencePlate]/usage/page.tsx
- app/components/private-cloud/sections/QuotasDescription.tsx
> chore(4494): add hard limit to metrics table

- localdev/nats-provision/Dockerfile
> fix(4589): add a command to install keycloak-admin to nats-provision docker file

- .github/actions/setup-npm/action.yml
- .tool-versions
- Makefile
- app/Dockerfile
- app/Dockerfile.db
- app/Dockerfile.email
- app/package.json
- app/pnpm-lock.yaml
- data-migrations/Dockerfile
- localdev/_packages/keycloak-admin/package.json
- localdev/_packages/keycloak-admin/pnpm-lock.yaml
- localdev/ches-mock/Dockerfile
- localdev/ches-mock/package.json
- localdev/ches-mock/pnpm-lock.yaml
- localdev/keycloak-provision/Dockerfile
- localdev/keycloak-provision/package.json
- localdev/keycloak-provision/pnpm-lock.yaml
- localdev/m365mock/Dockerfile
- localdev/m365mock/package.json
- localdev/m365mock/pnpm-lock.yaml
- localdev/nats-provision/Dockerfile
- localdev/nats-provision/package.json
- localdev/nats-provision/pnpm-lock.yaml
- pnpm-lock.yaml
The Dev and Test Deployment started failing somewhere between Dec 19 and Dec 31. We are reverting some of the changes made by renovate bot to fix it.
> fix(4602): revert the nodejs upgrade 22.12 to 22.10

- app/app/api/private-cloud/products/[licencePlate]/quota-change-status/route.ts
need to add `KLAB_METRICS_READER_TOKEN`. to `.env.local`
> fix(6058): add hardcoded LP and cluster for local getQuotaChangeStatus
